### PR TITLE
Add docker compose example

### PR DESCRIPTION
**Pull request by dprillxyz**
Added a new file called docker-compose.yml and edited the README.md file to provide a docker compose example in addition to the docker run example you already had. I'm using the docker compose solution to deploy your project currently, works great.

### CODE REVIEW

**Comment by kevinkk525** [comment]
Thank you for the PR.
I actually use it with docker-compose too but mine looks a bit different:

```
  storj-log-exporter:
    image: kevinkk525/storj-log-exporter:latest
    container_name: storj-grok-exporter1
    user: "1000:1000"
    restart: unless-stopped
    #ports:
    #  - 9144:9144
    volumes:
      - type: bind
        source: /sharedfolders/storjLogs/storj1
        target: /app/logs
    command: -config /app/config.yml 
    networks:
      - default
```

I'm not exposing ports as I run all docker-compose node stuff on the same network but that doesn't have to be in the README. I wasn't sure what to add so I don't make it too complicated for people as most will likely just use the docker run command.

Any comments about the differences between our approaches?
E.g. how command is used, exposing the port, the user environment, ... , why are you building it from the source instead of just using the docker image? (it's already a multi-platform build, no advantage in building locally)

**Comment by dprillxyz** [comment]
That's a fair point about not exposing the ports, I don't have mine exposed either for the same reasons as you. I think the example would be better with the ports commented out.

I only built from source because I didn't look to see if there was a build available to pull, just followed the readme. I'll definitely swap to the multi-platform build in the example and here in my environment.

I'll also modify the example I was using to make it more inline with yours. I can see how my first attempt could complicate the setup for a new user.

**Comment by kevinkk525** [comment]
Looks good. Might be good to add some comments to the Readme like: "alternatively you can add the following docker-compose to your docker-compose config for your storagenode:"
Just to make it easier for people that don't immediately understand what that section is about. What do you think?

**Comment by dprillxyz** [comment]
Yeah, good call. That section was in need of some context

**Pull request merged**
